
networks:
  localnetwork:
    driver: bridge

services:
  db:
    image: postgres:16
    restart: always
    networks:
      - localnetwork
    env_file:
      - .env
    container_name: template-db-1
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-template}"]
      interval: 5s
      timeout: 3s
      retries: 5
  
  template-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: template-app
    restart: unless-stopped
    networks:
      - localnetwork
    ports:
      - "${APP_PORT:-8080}:8080"
    depends_on:
      db:
        condition: service_healthy

  goose:
    image: gomicro/goose:3.25.0
    container_name: goose
    environment:
      GOOSE_DRIVER: ${GOOSE_DRIVER}
      GOOSE_DBSTRING: ${PG_DSN}
      GOOSE_MIGRATION_DIR: ${GOOSE_MIGRATION_DIR}
      GOOSE_TABLE: ${GOOSE_TABLE}
    volumes:
      - ./migrations:/migrations
    networks:
      - localnetwork
    entrypoint: goose up
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data: