// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: template.sql

package sqlc

import (
	"context"
)

const template = `-- name: template :many
SELECT id FROM template
`

func (q *Queries) template(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, template)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
